"MDF"= 4.8mm
"Foamcore"= 4.6mm
"GMaterial"= "MDF"
"D1@Boss-Extrude1"="GMaterial"
"PCB" = 1.6mm
"BaseWidth" = 10in
"SkidLength" = 1in
"SkidClearance" = 0.4in
"D1@Sketch12"="SkidLength"
"D2@Sketch12"="GMaterial"
"D4@Sketch12"="BaseWidth"/2 -"GMaterial"/2
"MotorMountLength" = 2in
"MotorMountWidth" = "GMaterial"
"MotorMountHeight" = 2.25in
"D1@Sketch13"="GMaterial"
"D2@Sketch13"="SkidLength"
"D4@Sketch13"="BaseWidth"/2 - "GMaterial"/2
"UnoStackWidth" = 77.4mm
"UnoStackLength" = 79.8mm
"UnoStackHeight" = 34.2mm
"TallHexRiserHeight" = 22.2mm
"PingPongBallSize" = 40mm
"BarrelLength" = 9in
"BarrelSize" = "PingPongBallSize"
"PlatformLength" = 4in
"PlatformWidth" = 6in
"WheelDiameter"=2.99213
"ServoMountHeight"=2.49223
"ServoGearHeight" = 0.95330261in
"ServoMountLength"= 1.53774
"PivotHoleRadius"= 0.616358
"PlatformMountHeight" = 3.19
"TensionOffSet"= .3mm
"MotorMountWedge"=0.333333
"LaserCutterOffset"= .3mm
"BumperWidth"=11
"PitcherWheelCompression" = 2.5mm
"PitchingWheelWidth" = 26.2mm
"PitchingWheelDiameter" = 65.5mm
"PitchingWheelMountOffset" = 8.4mm
"PitchingWheelInnerDiameter" = 45.5mm
"PitchingWheelBoltShoulder" = 4.5mm
"BrassCouplingLength" = 18mm
"PitchingMotorHeight" = 57.0mm
"PitchingMotorShaftTopHeight" = "PitchingMotorHeight" - 44.1mm
"PitchingMotorBodyHeight" = 38mm
"PitchingMotorTopShoulderHeight" = 40.6mm - "PitchingMotorBodyHeight" 
"PitchingMotorBottomShoulderHeight" = 40.2mm - "PitchingMotorBodyHeight"
"PitchingMotorBottomShaftHeight" = "PitchingMotorHeight" - "PitchingMotorShaftTopHeight" - "PitchingMotorTopShoulderHeight" - "PitchingMotorBodyHeight" - "PitchingMotorBottomShoulderHeight"
"PitchingMotorShaftDiameter" = 2.2mm
"PitchingMotorBodyDiameter" = 27.4mm
"PitchingMotorTopShoulderDiameter" = 9.8mm
"PitchingMotorBottomShoulderDiameter" = 9.8mm
"BrassCouplingHexSize" = 12mm
"BrassCouplingBoreSize" = 3.17mm
"PitchingMotorMountingHoleDistance" = 16mm
"Acrylic" = 4.4mm
"PitchingMotorDistance" = "PitchingWheelDiameter" + "PingPongBallSize" - "PitcherWheelCompression"*2
"PitchingMotorPlatformOffset"=1
"ServoPlatformOffset"=1.64173
"BallBearingDiameter" = 22mm
"BallBearingWidth" = 9mm
"BallBearingHexShoulder" = 9mm - 5.9mm
"BallBearingHexSize" = .36in
"PlatformMountFootLength"=0.857143
"WheelWidth"= 26mm
"ServoMountReductionBackHeight"=2.25
"PlatformBottomWidthThird" =  0.857143in
"PlatformMountBackReductionHeight"= 2.5in
"PlatformMountBackReductionWidth"= 3/7in
"PlatformMountFrontReductionWidth" =  1.46226in
"PlatformMountFrontReductionHeight" = 2.5in
