"MDF"= 4.8mm
"Foamcore"= 4.6mm
"PCB" = 1.6mm
"GMaterial"= "MDF"
"BaseWidth" = 10in
"SkidLength" = 1in
"SkidClearance" = 0.4in
"MotorMountLength" = 2in
"MotorMountWidth" = "GMaterial"
"MotorMountHeight" = 2.25in
"UnoStackWidth" = 77.4mm
"UnoStackLength" = 79.8mm
"UnoStackHeight" = 34.2mm
"TallHexRiserHeight" = 22.2mm
"PingPongBallSize" = 40mm
"BarrelLength" = 9in
"BarrelSize" = "PingPongBallSize"
"PlatformLength" = 4in
"PlatformWidth" = 6in
"WheelDiameter"=2.99213
"ServoMountLength"= 1.53774
"ServoGearHeight" = 0.95330261in
"PlatformMountHeight" = 3.19
"PivotHoleRadius"= 0.616358
"D1@Sketch1"= "MDF" + "PivotHoleRadius" + 3
"ServoMountReductionBackHeight"=2.25
"ServoMountHeight"=2.49223
"TensionOffSet"= .3mm
"MotorMountWedge"=0.333333
"LaserCutterOffset"= .3mm
"BumperWidth"=11
"PitcherWheelCompression" = 2.5mm
"PitchingWheelWidth" = 26.2mm
"PitchingWheelDiameter" = 65.5mm
"PitchingWheelMountOffset" = 8.4mm
"PitchingWheelInnerDiameter" = 45.5mm
"PitchingWheelBoltShoulder" = 4.5mm
"BrassCouplingLength" = 18mm
"PitchingMotorHeight" = 57.0mm
"PitchingMotorShaftTopHeight" = "PitchingMotorHeight" - 44.1mm
"PitchingMotorBodyHeight" = 38mm
"PitchingMotorTopShoulderHeight" = 40.6mm - "PitchingMotorBodyHeight" 
"PitchingMotorBottomShoulderHeight" = 40.2mm - "PitchingMotorBodyHeight"
"PitchingMotorBottomShaftHeight" = "PitchingMotorHeight" - "PitchingMotorShaftTopHeight" - "PitchingMotorTopShoulderHeight" - "PitchingMotorBodyHeight" - "PitchingMotorBottomShoulderHeight"
"PitchingMotorShaftDiameter" = 2.2mm
"PitchingMotorBodyDiameter" = 27.4mm
"PitchingMotorTopShoulderDiameter" = 9.8mm
"PitchingMotorBottomShoulderDiameter" = 9.8mm
"BrassCouplingHexSize" = 12mm
"BrassCouplingBoreSize" = 3.17mm
"PitchingMotorMountingHoleDistance" = 16mm
"Acrylic" = 4.4mm
"PitchingMotorDistance" = "PitchingWheelDiameter" + "PingPongBallSize" - "PitcherWheelCompression"*2
"PitchingMotorPlatformOffset"=1
"ServoPlatformOffset"=1.64173
"BallBearingDiameter" = 22mm
"BallBearingWidth" = 9mm
"BallBearingHexShoulder" = 9mm - 5.9mm
"BallBearingHexSize" = .36in
"WheelWidth"= 26mm
"PlatformMountBackReductionHeight"= 2.5in
"PlatformMountBackReductionWidth"= 3/7in
"PlatformMountFrontReductionWidth" =  1.46226in
"PlatformMountFrontReductionHeight" = 2.5in
"D1@Sketch5"="PlatformMountFrontReductionWidth"
"D2@Sketch5"="PlatformMountFrontReductionHeight"
"D1@Sketch7"="GMaterial"*2
"PlatformBottomWidthThird" =  0.857143in
"D2@Sketch7"="GMaterial"-"LaserCutterOffset"
"D3@Sketch7"="GMaterial"-"LaserCutterOffset"
"D4@Sketch7"="PlatformBottomWidthThird"/3
"D5@Sketch7"="PlatformBottomWidthThird"/3
